name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES}" >> .npmrc
      - name: ls
        run: cat .npmrc
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.READ_PACKAGES_PAT}}
      - name: Release
        run: npx semantic-release